services:
  prometheus-service:
    image: prom/prometheus
    container_name: prometheus-container
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo-service:
    image: grafana/tempo
    container_name: tempo-container
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # Zipkin

  loki-service:
    image: grafana/loki:main
    container_name: loki-container
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  grafana-service:
    image: grafana/grafana
    container_name: grafana-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  product-service:
    build: ./
    container_name: product-container
    depends_on:
      - tempo-service
      - loki-service
    restart: always
    ports:
      - "8081:8081"