apiVersion: 1

datasources:
  - name: prometheus-datasource
    type: prometheus
    access: proxy
    url: http://prometheus-container:9090
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: tempo-datasource
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo-container:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
      nodeGraph:
        enabled: true

  - name: loki-datasource
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki-container:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        -   datasourceUid: tempo
            matcherRegex: \[.+,(.+?),
            name: TraceID
            url: $${__value.raw}